### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by graywolf336** [mjovanovic0/rocketchat-remind-app#2]
Just a heads up, if you move the `@types/node` to be underneath the `devDependencies` the Marketplace compiler will pick it up and compile using the version you've provided instead of the standard one. I would highly recommend going this route so that when you do end up submitting it to Rocket.Chat's Marketplace the compiled version uses the same dependencies as when you're working on it locally. :)

**Comment by mjovanovic0** [comment]
Awesome!

Thanks for the tip. Will move it up, it must be that it get down in process of 'upgrading' dependencies to latest rc-apps.

Thanks again :)
